// Generated by CoffeeScript 1.6.3
(function() {
  var data, fs, html, jade, output, productData, s, schematicWidths, sku, template, templateFile, templateObj, urls;

  fs = require('fs');

  jade = require('jade');

  data = require('../out');

  templateFile = './template.jade';

  template = jade.compile(fs.readFileSync(templateFile), {
    filename: templateFile,
    pretty: false
  });

  schematicWidths = require('../data/site-schematicWidths');

  urls = require('../data/site-urls');

  s = 'sku\thtml\n';

  output = {};

  for (sku in data) {
    productData = data[sku];
    templateObj = {
      data: productData,
      dataset: data,
      sectionOrder: {
        features: ['features'],
        specifications: ['lockDimensions', 'schematic'],
        details: ['details'],
        bestUsedFors: ['bestUsedFors'],
        videos: ['videos']
      },
      isAvailable: function(keys, obj) {
        var length;
        length = (keys.filter(function(key) {
          return key in obj;
        })).length;
        return length > 0 && length === keys.length;
      },
      schematicWidths: schematicWidths,
      urls: urls,
      sku: sku
    };
    console.log(sku);
    html = template(templateObj).replace('\n', '');
    output[sku] = html;
    s = "" + s + sku + "\t" + html + "\n";
    fs.writeFileSync("./pages/" + sku + ".html", html, 'utf8');
  }

  fs.writeFileSync('./out.csv', s, 'utf8');

  fs.writeFileSync('./output.json', JSON.stringify(output), 'utf8');

}).call(this);
